# Generated by Django 5.1.2 on 2024-10-30 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Distribuidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('pais', models.CharField(max_length=100)),
                ('exportacion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Estanco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('localizacion', models.CharField(max_length=150)),
                ('distribuidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estanco', to='tabacosAPP.distribuidor')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=9)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('edad', models.PositiveIntegerField()),
                ('estanco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='tabacosAPP.estanco')),
            ],
        ),
    ]
