# Generated by Django 5.1.2 on 2024-11-14 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabacosAPP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='imagenCliente',
            field=models.URLField(blank=True, max_length=600, null=True),
        ),
    ]
