# Generated by Django 5.1.3 on 2024-11-15 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabacosAPP', '0002_cliente_imagencliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('imagenEstanco', models.URLField(blank=True, max_length=600, null=True)),
                ('distribuidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marca', to='tabacosAPP.distribuidor')),
                ('estanco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marcas', to='tabacosAPP.estanco')),
            ],
        ),
    ]
