# Generated by Django 5.1.3 on 2024-11-15 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabacosAPP', '0003_marca'),
    ]

    operations = [
        migrations.AddField(
            model_name='marca',
            name='tipo',
            field=models.CharField(choices=[('Cigarrillos', 'Cigarrillos'), ('Puros', 'Puros')], default='null', max_length=20),
            preserve_default=False,
        ),
    ]
