# Generated by Django 5.1.3 on 2024-11-15 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tabacosAPP', '0004_marca_tipo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marca',
            old_name='imagenEstanco',
            new_name='imagenMarca',
        ),
    ]
