# Generated by Django 5.1.3 on 2024-11-23 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabacosAPP', '0006_cigarrillo_puro'),
    ]

    operations = [
        migrations.AddField(
            model_name='cigarrillo',
            name='marca',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='cigarro', to='tabacosAPP.marca'),
        ),
        migrations.AddField(
            model_name='puro',
            name='marca',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='puro', to='tabacosAPP.marca'),
        ),
    ]
