# Generated by Django 5.1.3 on 2024-11-23 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabacosAPP', '0007_cigarrillo_marca_puro_marca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cigarrillo',
            name='precio',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='puro',
            name='precio',
            field=models.FloatField(),
        ),
    ]
