# Generated by Django 5.1.3 on 2024-11-24 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabacosAPP', '0008_alter_cigarrillo_precio_alter_puro_precio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marca',
            name='estanco',
        ),
        migrations.AddField(
            model_name='marca',
            name='estanco',
            field=models.ManyToManyField(to='tabacosAPP.estanco'),
        ),
    ]
