# Generated by Django 5.1.3 on 2024-12-04 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabacosAPP', '0009_remove_marca_estanco_marca_estanco'),
    ]

    operations = [
        migrations.AddField(
            model_name='distribuidor',
            name='imagenDistr',
            field=models.URLField(blank=True, max_length=600, null=True),
        ),
    ]
